export type MenuItemTypes = {
  key: string
  label: string
  isTitle?: boolean
  icon?: string
  url?: string
  badge?: {
    variant: string
    text: string
  }
  parentKey?: string
  target?: string
  children?: MenuItemTypes[]
  collapsed?: boolean
}

export const MENU: MenuItemTypes[] = [
  { key: 'navigation', label: 'Navigation', isTitle: true },
  {
    key: 'dashboards',
    label: 'Dashboards',
    isTitle: false,
    icon: 'ri-dashboard-line',
    badge: { variant: 'success', text: '3' },
    collapsed: true,
    children: [
      {
        key: 'ds-sales',
        label: 'Sales',
        url: '/dashboard/sales',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-crm',
        label: 'CRM',
        url: '/dashboard/crm',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-analytics',
        label: 'Analytics',
        url: '/dashboard/analytics',
        parentKey: 'dashboards',
      },
    ],
  },
  { key: 'apps', label: 'Apps', isTitle: true },
  {
    key: 'apps-chat',
    label: 'Chat',
    isTitle: false,
    icon: 'ri-message-2-line',
    url: '/apps/chat',
  },
  {
    key: 'apps-ecommerce',
    label: 'Ecommerce',
    isTitle: false,
    icon: 'ri-shopping-cart-2-line',
    badge: { variant: 'danger', text: 'New' },
    collapsed: true,
    children: [
      {
        key: 'ecommerce-products',
        label: 'Products List',
        url: '/ecommerce/products',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-products-grid',
        label: 'Products Grid',
        url: '/ecommerce/products-grid',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-detail',
        label: 'Product Detail',
        url: '/ecommerce/product-detail',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-product-create',
        label: 'Create Product',
        url: '/ecommerce/product-create',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-customers',
        label: 'Customers',
        url: '/ecommerce/customers',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-orders',
        label: 'Orders',
        url: '/ecommerce/orders',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-order-detail',
        label: 'Order Detail',
        url: '/ecommerce/orders-detail',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-sellers',
        label: 'Sellers',
        url: '/ecommerce/sellers',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-shopping-cart',
        label: 'Shopping Cart',
        url: '/ecommerce/cart',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-checkout',
        label: 'Checkout',
        url: '/ecommerce/checkout',
        parentKey: 'apps-ecommerce',
      },
    ],
  },
  {
    key: 'apps-calendar',
    label: 'Calendar',
    isTitle: false,
    icon: 'ri-calendar-2-line',
    url: '/apps/calendar',
  },
  {
    key: 'apps-email',
    label: 'Email',
    isTitle: false,
    icon: 'ri-mail-line',
    collapsed: true,
    children: [
      {
        key: 'email-inbox',
        label: 'Inbox',
        url: '/email/inbox',
        parentKey: 'apps-email',
      },
      {
        key: 'email-read-email',
        label: 'Read Email',
        url: '/email/read',
        parentKey: 'apps-email',
      },
      {
        key: 'email-templates',
        label: 'Email Templates',
        url: '/email/templates',
        parentKey: 'apps-email',
      },
    ],
  },
  {
    key: 'apps-companies',
    label: 'Companies',
    isTitle: false,
    icon: 'ri-building-4-line',
    url: '/apps/companies',
  },
  {
    key: 'apps-tasks',
    label: 'Tasks',
    isTitle: false,
    icon: 'ri-task-line',
    collapsed: true,
    children: [
      {
        key: 'task-list',
        label: 'List',
        url: '/task/list',
        parentKey: 'apps-tasks',
      },
      {
        key: 'task-details',
        label: 'Details',
        url: '/task/details',
        parentKey: 'apps-tasks',
      },
      {
        key: 'task-kanban',
        label: 'Kanban Board',
        url: '/task/kanban-board',
        parentKey: 'apps-tasks',
      },
    ],
  },
  {
    key: 'apps-tickets',
    label: 'Tickets',
    isTitle: false,
    icon: 'ri-customer-service-2-line',
    url: '/apps/tickets',
  },
  {
    key: 'apps-contacts',
    label: 'Contacts',
    isTitle: false,
    icon: 'ri-profile-line',
    collapsed: true,
    children: [
      {
        key: 'contacts-list',
        label: 'Members List',
        url: '/contacts/list',
        parentKey: 'apps-contacts',
      },
      {
        key: 'contacts-profile',
        label: 'Profile',
        url: '/contacts/profile',
        parentKey: 'apps-contacts',
      },
    ],
  },
  {
    key: 'apps-file-manager',
    label: 'File Manager',
    isTitle: false,
    icon: 'ri-folders-line',
    url: '/apps/file-manager',
  },
  { key: 'custom', label: 'Custom', isTitle: true },
  {
    key: 'auth',
    label: 'Auth Pages',
    isTitle: false,
    icon: 'ri-shield-user-line',
    collapsed: true,
    children: [
      {
        key: 'auth-login',
        label: 'Log In',
        url: '/auth/login',
        parentKey: 'auth',
      },
      {
        key: 'auth-login-2',
        label: 'Log In 2',
        url: '/auth/login-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-register',
        label: 'Register',
        url: '/auth/register',
        parentKey: 'auth',
      },
      {
        key: 'auth-register-2',
        label: 'Register 2',
        url: '/auth/register-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-signin-signup',
        label: 'Signin-Signup',
        url: '/auth/signin-signup',
        parentKey: 'auth',
      },
      {
        key: 'auth-signin-signup-2',
        label: 'Signin-Signup 2',
        url: '/auth/signin-signup-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-recoverpw',
        label: 'Recover Password',
        url: '/auth/recoverpw',
        parentKey: 'auth',
      },
      {
        key: 'auth-recoverpw-2',
        label: 'Recover Password 2',
        url: '/auth/recoverpw-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-lock-screen',
        label: 'Lock Screen',
        url: '/auth/lock-screen',
        parentKey: 'auth',
      },
      {
        key: 'auth-lock-screen-2',
        label: 'Lock Screen 2',
        url: '/auth/lock-screen-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-logout',
        label: 'Logout',
        url: '/auth/logout',
        parentKey: 'auth',
      },
      {
        key: 'auth-logout-2',
        label: 'Logout 2',
        url: '/auth/logout-2',
        parentKey: 'auth',
      },
      {
        key: 'auth-confirm-mail',
        label: 'Confirm Mail',
        url: '/auth/confirm-mail',
        parentKey: 'auth',
      },
      {
        key: 'auth-confirm-mail-2',
        label: 'Confirm Mail 2',
        url: '/auth/confirm-mail-2',
        parentKey: 'auth',
      },
    ],
  },
  {
    key: 'extra-pages',
    label: 'Extra Pages',
    isTitle: false,
    icon: 'ri-pages-line',
    collapsed: true,
    children: [
      {
        key: 'page-starter',
        label: 'Starter',
        url: '/pages/starter',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-timeline',
        label: 'Timeline',
        url: '/pages/timeline',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-sitemap',
        label: 'Sitemap',
        url: '/pages/sitemap',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-invoice',
        label: 'Invoice',
        url: '/pages/invoice',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-faq',
        label: 'FAQs',
        url: '/pages/faqs',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-search-result',
        label: 'Search Results',
        url: '/pages/search-results',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-pricing',
        label: 'Pricing',
        url: '/pages/pricing',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-maintenance',
        label: 'Maintenance',
        url: '/pages/maintenance',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-coming-soon',
        label: 'Coming Soon',
        url: '/pages/coming-soon',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-gallery',
        label: 'Gallery',
        url: '/pages/gallery',
        parentKey: 'extra-pages',
      },

      {
        key: 'page-error-404',
        label: 'Error - 404',
        url: '/pages/404',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-error-404-alt',
        label: 'Error - 404-alt',
        url: '/pages/404-alt',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-error-500',
        label: 'Error - 500',
        url: '/pages/500',
        parentKey: 'extra-pages',
      },
    ],
  },
  { key: 'components', label: 'Components', isTitle: true },
  {
    key: 'base-ui',
    label: 'Base UI',
    isTitle: false,
    icon: 'ri-pencil-ruler-2-line',
    collapsed: true,
    children: [
      {
        key: 'base-ui-avatars',
        label: 'Avatars',
        url: '/ui/avatars',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-buttons',
        label: 'Buttons',
        url: '/ui/buttons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-cards',
        label: 'Cards',
        url: '/ui/cards',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-carousel',
        label: 'Carousel',
        url: '/ui/carousel',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-dropdown',
        label: 'Dropdowns',
        url: '/ui/dropdowns',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-embedvideo',
        label: 'Embed Video',
        url: '/ui/video',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-general',
        label: 'General UI',
        url: '/ui/general',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-grid',
        label: 'Grid',
        url: '/ui/grid',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-images',
        label: 'Images',
        url: '/ui/images',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-list-group',
        label: 'List Group',
        url: '/ui/list-group',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-modals',
        label: 'Modals',
        url: '/ui/modals',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-notifications',
        label: 'Notifications',
        url: '/ui/notifications',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-offcanvas',
        label: 'Offcanvas',
        url: '/ui/offcanvas',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-placeholders',
        label: 'Placeholders',
        url: '/ui/placeholders',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-portlets',
        label: 'Portlets',
        url: '/ui/portlets',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-progress',
        label: 'Progress',
        url: '/ui/progress',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-ribbons',
        label: 'Ribbons',
        url: '/ui/ribbons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-spinners',
        label: 'Spinners',
        url: '/ui/spinners',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tabs-accordions',
        label: 'Tabs & Accordions',
        url: '/ui/tabs-accordions',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tooltips-popovers',
        label: 'Tooltips & Popovers',
        url: '/ui/tooltips-popovers',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-typography',
        label: 'Typography',
        url: '/ui/typography',
        parentKey: 'base-ui',
      },
    ],
  },
  {
    key: 'extended-ui',
    label: 'Extended UI',
    isTitle: false,
    icon: 'ri-stack-line',
    badge: { variant: 'info', text: 'Hot' },
    collapsed: true,
    children: [
      {
        key: 'extended-ui-range-slider',
        label: 'Range Sliders',
        url: '/extended/range-slider',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-sweet-alert',
        label: 'Sweet Alert',
        url: '/extended/sweet-alert',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-tour',
        label: 'Tour Page',
        url: '/extended/tour',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-scrollspy',
        label: 'Scrollspy',
        url: '/extended/scrollspy',
        parentKey: 'extended-ui',
      },
    ],
  },
  {
    key: 'widgets',
    label: 'Widgets',
    isTitle: false,
    icon: 'ri-honour-line',
    url: '/apps/widgets',
  },
  {
    key: 'icons',
    label: 'Icons',
    isTitle: false,
    icon: 'ri-markup-line',
    collapsed: true,
    children: [
      {
        key: 'icon-feather',
        label: 'Feather',
        url: '/icons/feather',
        parentKey: 'icons',
      },
      {
        key: 'icon-remiix',
        label: 'Remix',
        url: '/icons/remix',
        parentKey: 'icons',
      },
      {
        key: 'icon-boxicons',
        label: 'Boxicons',
        url: '/icons/boxicons',
        parentKey: 'icons',
      },
      {
        key: 'icon-mdiicons',
        label: 'Material Design Icons',
        url: '/icons/mdi',
        parentKey: 'icons',
      },
      {
        key: 'icon-font-awesome',
        label: 'Font Awesome 5',
        url: '/icons/font-awesome',
        parentKey: 'icons',
      },
      {
        key: 'icon-weather',
        label: 'Weather',
        url: '/icons/weather',
        parentKey: 'icons',
      },
    ],
  },
  {
    key: 'forms',
    label: 'Forms',
    isTitle: false,
    icon: 'ri-eraser-line',
    collapsed: true,
    children: [
      {
        key: 'form-basic',
        label: 'General Elements',
        url: '/forms/elements',
        parentKey: 'forms',
      },
      {
        key: 'form-advanced',
        label: 'Advanced',
        url: '/forms/advanced',
        parentKey: 'forms',
      },
      {
        key: 'form-validation',
        label: 'Validation',
        url: '/forms/validation',
        parentKey: 'forms',
      },
      {
        key: 'form-pickers',
        label: 'Pickers',
        url: '/forms/pickers',
        parentKey: 'forms',
      },
      {
        key: 'form-wizard',
        label: 'Wizard',
        url: '/forms/wizard',
        parentKey: 'forms',
      },
      {
        key: 'form-masks',
        label: 'Masks',
        url: '/forms/masks',
        parentKey: 'forms',
      },
      {
        key: 'form-quilljs',
        label: 'Quilljs Editor',
        url: '/forms/quilljs',
        parentKey: 'forms',
      },
      {
        key: 'form-file-uploads',
        label: 'File Uploads',
        url: '/forms/file-uploads',
        parentKey: 'forms',
      },
    ],
  },
  {
    key: 'tables',
    label: 'Tables',
    isTitle: false,
    icon: 'ri-table-line',
    collapsed: true,
    children: [
      {
        key: 'table-basic',
        label: 'Basic Tables',
        url: '/tables/basic',
        parentKey: 'tables',
      },
      {
        key: 'table-data-table',
        label: 'Data Tables',
        url: '/tables/datatables',
        parentKey: 'tables',
      },
    ],
  },
  {
    key: 'charts',
    label: 'Charts',
    isTitle: false,
    icon: 'ri-bar-chart-line',
    collapsed: true,
    children: [
      {
        key: 'chart-apex',
        label: 'Apex Charts',
        url: '/charts/apex',
        parentKey: 'charts',
      },
      {
        key: 'chart-chartjs',
        label: 'Chartjs',
        url: '/charts/chartjs',
        parentKey: 'charts',
      },
    ],
  },
  {
    key: 'maps',
    label: 'Maps',
    isTitle: false,
    icon: 'ri-map-pin-line',
    collapsed: true,
    children: [
      {
        key: 'maps-googlemaps',
        label: 'Google Maps',
        url: '/maps/google',
        parentKey: 'maps',
      },
      {
        key: 'maps-vector',
        label: 'Vector Maps',
        url: '/maps/vector',
        parentKey: 'maps',
      },
    ],
  },
  {
    key: 'multi-level',
    label: 'Multi Level',
    isTitle: false,
    icon: 'ri-share-line',
    collapsed: true,
    children: [
      {
        key: 'second-level',
        label: 'Second Level',
        parentKey: 'multi-level',
        collapsed: true,
        children: [
          {
            key: 'item-1',
            label: 'Item 1',
            parentKey: 'second-level',
          },
          {
            key: 'item-2',
            label: 'Item 2',
            parentKey: 'second-level',
          },
        ],
      },
      {
        key: 'third-level',
        label: 'Third Level',
        parentKey: 'multi-level',
        collapsed: true,
        children: [
          {
            key: 'item-1',
            label: 'Item 1',
            parentKey: 'third-level',
          },
          {
            key: 'item-2',
            label: 'Item 2',
            parentKey: 'third-level',
            collapsed: true,
            children: [
              {
                key: 'item-1',
                label: 'Item 1',
                parentKey: 'menu-levels-1-1',
              },
              {
                key: 'item-2',
                label: 'Item 2',
                parentKey: 'menu-levels-1-1',
              },
            ],
          },
        ],
      },
    ],
  },
]

export const HORIZONTAL_MENU_ITEMS: MenuItemTypes[] = [
  {
    key: 'dashboards',
    icon: 'ri-dashboard-line',
    label: 'Dashboard',
    isTitle: true,
    children: [
      {
        key: 'ds-sales',
        label: 'Sales',
        url: '/dashboard/sales',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-crm',
        label: 'CRM',
        url: '/dashboard/crm',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-analytics',
        label: 'Analytics',
        url: '/dashboard/analytics',
        parentKey: 'dashboards',
      },
    ],
  },
  {
    key: 'apps',
    icon: 'ri-apps-2-line',
    label: 'Apps',
    isTitle: true,
    children: [
      {
        key: 'apps-calendar',
        label: 'Calendar',
        isTitle: false,
        icon: 'ri-calendar-2-line',
        url: '/apps/calendar',
        parentKey: 'apps',
      },
      {
        key: 'apps-chat',
        label: 'Chat',
        isTitle: false,
        icon: 'ri-message-2-line',
        url: '/apps/chat',
        parentKey: 'apps',
      },

      {
        key: 'apps-ecommerce',
        label: 'Ecommerce',
        isTitle: false,
        icon: 'ri-shopping-cart-2-line',
        parentKey: 'apps',
        children: [
          {
            key: 'ecommerce-products',
            label: 'Products List',
            url: '/ecommerce/products',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-products-grid',
            label: 'Products Grid',
            url: '/ecommerce/products-grid',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-detail',
            label: 'Product Detail',
            url: '/ecommerce/product-detail',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-product-create',
            label: 'Create Product',
            url: '/ecommerce/product-create',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-customers',
            label: 'Customers',
            url: '/ecommerce/customers',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-orders',
            label: 'Orders',
            url: '/ecommerce/orders',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-order-detail',
            label: 'Order Detail',
            url: '/ecommerce/orders-detail',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-sellers',
            label: 'Sellers',
            url: '/ecommerce/sellers',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-shopping-cart',
            label: 'Shopping Cart',
            url: '/ecommerce/cart',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-checkout',
            label: 'Checkout',
            url: '/ecommerce/checkout',
            parentKey: 'apps-ecommerce',
          },
        ],
      },
      {
        key: 'apps-email',
        label: 'Email',
        isTitle: false,
        icon: 'ri-mail-line',
        parentKey: 'apps',
        children: [
          {
            key: 'email-inbox',
            label: 'Inbox',
            url: '/email/inbox',
            parentKey: 'apps-email',
          },
          {
            key: 'email-read-email',
            label: 'Read Email',
            url: '/email/read',
            parentKey: 'apps-email',
          },
          {
            key: 'email-templates',
            label: 'Email Templates',
            url: '/email/templates',
            parentKey: 'apps-email',
          },
        ],
      },
      {
        key: 'apps-companies',
        label: 'Companies',
        isTitle: false,
        icon: 'ri-building-4-line',
        url: '/apps/companies',
        parentKey: 'apps',
      },
      {
        key: 'apps-tasks',
        label: 'Tasks',
        isTitle: false,
        icon: 'ri-task-line',
        parentKey: 'apps',
        children: [
          {
            key: 'task-list',
            label: 'List',
            url: '/task/list',
            parentKey: 'apps-tasks',
          },
          {
            key: 'task-details',
            label: 'Details',
            url: '/task/details',
            parentKey: 'apps-tasks',
          },
          {
            key: 'task-kanban',
            label: 'Kanban Board',
            url: '/task/kanban-board',
            parentKey: 'apps-tasks',
          },
        ],
      },
      {
        key: 'apps-contacts',
        label: 'Contacts',
        isTitle: false,
        icon: 'ri-profile-line',
        parentKey: 'apps',
        children: [
          {
            key: 'contacts-list',
            label: 'Members List',
            url: '/contacts/list',
            parentKey: 'apps-contacts',
          },
          {
            key: 'contacts-profile',
            label: 'Profile',
            url: '/contacts/profile',
            parentKey: 'apps-contacts',
          },
        ],
      },
      {
        key: 'apps-file-manager',
        label: 'File Manager',
        isTitle: false,
        icon: 'ri-folders-line',
        url: '/apps/file-manager',
        parentKey: 'apps',
      },
      {
        key: 'apps-tickets',
        label: 'Tickets',
        isTitle: false,
        icon: 'ri-customer-service-2-line',
        url: '/apps/tickets',
        parentKey: 'apps',
      },
    ],
  },
  {
    key: 'base-ui',
    icon: 'ri-pencil-ruler-2-line',
    label: 'UI Elements',
    isTitle: true,
    children: [
      {
        key: 'base-ui-avatars',
        label: 'Avatars',
        url: '/ui/avatars',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-buttons',
        label: 'Buttons',
        url: '/ui/buttons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-cards',
        label: 'Cards',
        url: '/ui/cards',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-carousel',
        label: 'Carousel',
        url: '/ui/carousel',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-dropdown',
        label: 'Dropdowns',
        url: '/ui/dropdowns',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-embedvideo',
        label: 'Embed Video',
        url: '/ui/video',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-general',
        label: 'General UI',
        url: '/ui/general',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-grid',
        label: 'Grid',
        url: '/ui/grid',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-images',
        label: 'Images',
        url: '/ui/images',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-listgroup',
        label: 'List Group',
        url: '/ui/listgroup',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-modals',
        label: 'Modals',
        url: '/ui/modals',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-notifications',
        label: 'Notifications',
        url: '/ui/notifications',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-offcanvas',
        label: 'Offcanvas',
        url: '/ui/offcanvas',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-placeholders',
        label: 'Placeholders',
        url: '/ui/placeholders',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-portlets',
        label: 'Portlets',
        url: '/ui/portlets',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-progress',
        label: 'Progress',
        url: '/ui/progress',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-ribbons',
        label: 'Ribbons',
        url: '/ui/ribbons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-spinners',
        label: 'Spinners',
        url: '/ui/spinners',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tabs-accordions',
        label: 'Tabs & Accordions',
        url: '/ui/tabs-accordions',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tooltips-popovers',
        label: 'Tooltips & Popovers',
        url: '/ui/tooltips-popovers',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-typography',
        label: 'Typography',
        url: '/ui/typography',
        parentKey: 'base-ui',
      },
    ],
  },
  {
    key: 'components',
    icon: 'ri-stack-line',
    label: 'Components',
    isTitle: true,
    children: [
      {
        key: 'extended-ui',
        label: 'Extended UI',
        isTitle: false,
        icon: 'ri-stack-line',
        badge: { variant: 'info', text: 'Hot' },
        parentKey: 'components',
        children: [
          {
            key: 'extended-ui-range-slider',
            label: 'Range Sliders',
            url: '/extended/range-slider',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-sweet-alert',
            label: 'Sweet Alert',
            url: '/extended/sweet-alert',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-tour',
            label: 'Tour Page',
            url: '/extended/tour',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-scrollspy',
            label: 'Scrollspy',
            url: '/extended/scrollspy',
            parentKey: 'extended-ui',
          },
        ],
      },
      {
        key: 'widgets',
        label: 'Widgets',
        isTitle: false,
        icon: 'ri-honour-line',
        url: '/apps/widgets',
        parentKey: 'components',
      },
      {
        key: 'forms',
        label: 'Forms',
        isTitle: false,
        icon: 'ri-eraser-line',
        parentKey: 'components',
        children: [
          {
            key: 'form-basic',
            label: 'General Elements',
            url: '/forms/elements',
            parentKey: 'forms',
          },
          {
            key: 'form-advanced',
            label: 'Advanced',
            url: '/forms/advanced',
            parentKey: 'forms',
          },
          {
            key: 'form-validation',
            label: 'Validation',
            url: '/forms/validation',
            parentKey: 'forms',
          },
          {
            key: 'form-pickers',
            label: 'Pickers',
            url: '/forms/pickers',
            parentKey: 'forms',
          },
          {
            key: 'form-wizard',
            label: 'Wizard',
            url: '/forms/wizard',
            parentKey: 'forms',
          },
          {
            key: 'form-masks',
            label: 'Masks',
            url: '/forms/masks',
            parentKey: 'forms',
          },
          {
            key: 'form-quilljs',
            label: 'Quilljs Editor',
            url: '/forms/quilljs',
            parentKey: 'forms',
          },
          {
            key: 'form-file-uploads',
            label: 'File Uploads',
            url: '/forms/file-uploads',
            parentKey: 'forms',
          },
        ],
      },
      {
        key: 'charts',
        label: 'Charts',
        isTitle: false,
        icon: 'ri-bar-chart-line',
        parentKey: 'components',
        children: [
          {
            key: 'chart-apex',
            label: 'Apex Charts',
            url: '/charts/apex',
            parentKey: 'charts',
          },
          {
            key: 'chart-chartjs',
            label: 'Chartjs',
            url: '/charts/chartjs',
            parentKey: 'charts',
          },
        ],
      },
      {
        key: 'tables',
        label: 'Tables',
        isTitle: false,
        icon: 'ri-table-line',
        collapsed: true,
        children: [
          {
            key: 'table-basic',
            label: 'Basic Tables',
            url: '/tables/basic',
            parentKey: 'tables',
          },
          {
            key: 'table-data-table',
            label: 'Data Tables',
            url: '/tables/datatables',
            parentKey: 'tables',
          },
        ],
      },
      {
        key: 'icons',
        label: 'Icons',
        isTitle: false,
        icon: 'ri-markup-line',
        collapsed: true,
        children: [
          {
            key: 'icon-feather',
            label: 'Feather',
            url: '/icons/feather',
            parentKey: 'icons',
          },
          {
            key: 'icon-remiix',
            label: 'Remix',
            url: '/icons/remix',
            parentKey: 'icons',
          },
          {
            key: 'icon-boxicons',
            label: 'Boxicons',
            url: '/icons/boxicons',
            parentKey: 'icons',
          },
          {
            key: 'icon-mdiicons',
            label: 'Material Design Icons',
            url: '/icons/mdi',
            parentKey: 'icons',
          },
          {
            key: 'icon-font-awesome',
            label: 'Font Awesome 5',
            url: '/icons/font-awesome',
            parentKey: 'icons',
          },
          {
            key: 'icon-weather',
            label: 'Weather',
            url: '/icons/weather',
            parentKey: 'icons',
          },
        ],
      },
      {
        key: 'maps',
        label: 'Maps',
        isTitle: false,
        icon: 'ri-map-pin-line',
        parentKey: 'components',
        children: [
          {
            key: 'maps-googlemaps',
            label: 'Google Maps',
            url: '/maps/google',
            parentKey: 'maps',
          },
          {
            key: 'maps-vector',
            label: 'Vector Maps',
            url: '/maps/vector',
            parentKey: 'maps',
          },
        ],
      },
    ],
  },
  {
    key: 'pages',
    icon: 'ri-pages-line',
    label: 'Pages',
    isTitle: true,
    children: [
      {
        key: 'auth-1',
        label: 'Auth Style 1',
        isTitle: false,
        parentKey: 'pages',
        children: [
          {
            key: 'auth-login',
            label: 'Log In',
            url: '/auth/login',
            parentKey: 'auth',
          },
          {
            key: 'auth-register',
            label: 'Register',
            url: '/auth/register',
            parentKey: 'auth',
          },
          {
            key: 'auth-signin-signup',
            label: 'Signin-Signup',
            url: '/auth/signin-signup',
            parentKey: 'auth',
          },
          {
            key: 'auth-recoverpw',
            label: 'Recover Password',
            url: '/auth/recoverpw',
            parentKey: 'auth',
          },
          {
            key: 'auth-lock-screen',
            label: 'Lock Screen',
            url: '/auth/lock-screen',
            parentKey: 'auth',
          },
          {
            key: 'auth-logout',
            label: 'Logout',
            url: '/auth/logout',
            parentKey: 'auth',
          },
          {
            key: 'auth-confirm-mail',
            label: 'Confirm Mail',
            url: '/auth/confirm-mail',
            parentKey: 'auth',
          },
        ],
      },
      {
        key: 'auth-2',
        label: 'Auth Style 2',
        isTitle: false,
        parentKey: 'pages',
        children: [
          {
            key: 'auth-login-2',
            label: 'Log In 2',
            url: '/auth/login-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-register-2',
            label: 'Register 2',
            url: '/auth/register-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-signin-signup-2',
            label: 'Signin-Signup 2',
            url: '/auth/signin-signup-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-recoverpw-2',
            label: 'Recover Password 2',
            url: '/auth/recoverpw-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-lock-screen-2',
            label: 'Lock Screen 2',
            url: '/auth/lock-screen-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-logout-2',
            label: 'Logout 2',
            url: '/auth/logout-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-confirm-mail-2',
            label: 'Confirm Mail 2',
            url: '/auth/confirm-mail-2',
            parentKey: 'auth',
          },
        ],
      },
      {
        key: 'error-pages',
        label: 'Errors',
        isTitle: false,
        parentKey: 'pages',
        children: [
          {
            key: 'page-error-404',
            label: 'Error - 404',
            url: '/pages/404',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-error-404-alt',
            label: 'Error - 404-alt',
            url: '/pages/404-alt',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-error-500',
            label: 'Error - 500',
            url: '/pages/500',
            parentKey: 'extra-pages',
          },
        ],
      },
      {
        key: 'extra-pages',
        label: 'Utility',
        isTitle: false,
        parentKey: 'pages',
        children: [
          {
            key: 'page-starter',
            label: 'Starter',
            url: '/pages/starter',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-timeline',
            label: 'Timeline',
            url: '/pages/timeline',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-sitemap',
            label: 'Sitemap',
            url: '/pages/sitemap',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-invoice',
            label: 'Invoice',
            url: '/pages/invoice',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-faq',
            label: 'FAQs',
            url: '/pages/faqs',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-search-result',
            label: 'Search Results',
            url: '/pages/search-results',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-pricing',
            label: 'Pricing',
            url: '/pages/pricing',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-maintenance',
            label: 'Maintenance',
            url: '/pages/maintenance',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-coming-soon',
            label: 'Coming Soon',
            url: '/pages/coming-soon',
            parentKey: 'extra-pages',
          },
          {
            key: 'page-gallery',
            label: 'Gallery',
            url: '/pages/gallery',
            parentKey: 'extra-pages',
          },
        ],
      },
    ],
  },
]

export const TWO_COl_MENU_ITEMS: MenuItemTypes[] = [
  {
    key: 'dashboards',
    icon: 'ri-dashboard-line',
    label: 'Dashboard',
    isTitle: true,
    children: [
      {
        key: 'ds-sales',
        label: 'Sales',
        url: '/dashboard/sales',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-crm',
        label: 'CRM',
        url: '/dashboard/crm',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-analytics',
        label: 'Analytics',
        url: '/dashboard/analytics',
        parentKey: 'dashboards',
      },
    ],
  },
  {
    key: 'apps',
    icon: 'ri-apps-2-line',
    label: 'Apps',
    isTitle: true,
    children: [
      {
        key: 'apps-calendar',
        label: 'Calendar',
        isTitle: false,
        icon: 'ri-calendar-2-line',
        url: '/apps/calendar',
        parentKey: 'apps',
      },
      {
        key: 'apps-chat',
        label: 'Chat',
        isTitle: false,
        icon: 'ri-message-2-line',
        url: '/apps/chat',
        parentKey: 'apps',
      },
      {
        key: 'apps-ecommerce',
        label: 'Ecommerce',
        isTitle: false,
        icon: 'ri-shopping-cart-2-line',
        parentKey: 'apps',
        collapsed: true,
        children: [
          {
            key: 'ecommerce-products',
            label: 'Products List',
            url: '/ecommerce/products',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-products-grid',
            label: 'Products Grid',
            url: '/ecommerce/products-grid',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-detail',
            label: 'Product Detail',
            url: '/ecommerce/product-detail',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-product-create',
            label: 'Create Product',
            url: '/ecommerce/product-create',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-customers',
            label: 'Customers',
            url: '/ecommerce/customers',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-orders',
            label: 'Orders',
            url: '/ecommerce/orders',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-order-detail',
            label: 'Order Detail',
            url: '/ecommerce/order/detail',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-sellers',
            label: 'Sellers',
            url: '/ecommerce/sellers',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-shopping-cart',
            label: 'Shopping Cart',
            url: '/ecommerce/shopping-cart',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-checkout',
            label: 'Checkout',
            url: '/ecommerce/checkout',
            parentKey: 'apps-ecommerce',
          },
        ],
      },

      {
        key: 'apps-email',
        label: 'Email',
        isTitle: false,
        icon: 'ri-mail-line',
        parentKey: 'apps',
        collapsed: true,
        children: [
          {
            key: 'email-inbox',
            label: 'Inbox',
            url: '/email/inbox',
            parentKey: 'apps-email',
          },
          {
            key: 'email-read-email',
            label: 'Read Email',
            url: '/email/details',
            parentKey: 'apps-email',
          },
          {
            key: 'email-templates',
            label: 'Email Templates',
            url: '/email/templates',
            parentKey: 'apps-email',
          },
        ],
      },
      {
        key: 'apps-companies',
        label: 'Companies',
        isTitle: false,
        icon: 'ri-building-4-line',
        url: '/apps/companies',
        parentKey: 'apps',
      },
      {
        key: 'apps-tasks',
        label: 'Tasks',
        isTitle: false,
        icon: 'ri-task-line',
        parentKey: 'apps',
        collapsed: true,
        children: [
          {
            key: 'task-list',
            label: 'List',
            url: '/tasks/list',
            parentKey: 'apps-tasks',
          },
          {
            key: 'task-details',
            label: 'Details',
            url: '/tasks/details',
            parentKey: 'apps-tasks',
          },
          {
            key: 'task-kanban',
            label: 'Kanban Board',
            url: '/tasks/kanban-board',
            parentKey: 'apps-tasks',
          },
        ],
      },
      {
        key: 'apps-contacts',
        label: 'Contacts',
        isTitle: false,
        icon: 'ri-profile-line',
        parentKey: 'apps',
        collapsed: true,
        children: [
          {
            key: 'contacts-list',
            label: 'Members List',
            url: '/contacts/list',
            parentKey: 'apps-contacts',
          },
          {
            key: 'contacts-profile',
            label: 'Profile',
            url: '/contacts/profile',
            parentKey: 'apps-contacts',
          },
        ],
      },
      {
        key: 'apps-file-manager',
        label: 'File Manager',
        isTitle: false,
        icon: 'ri-folders-line',
        url: '/apps/file-manager',
        parentKey: 'apps',
      },
      {
        key: 'apps-tickets',
        label: 'Tickets',
        isTitle: false,
        icon: 'ri-customer-service-2-line',
        url: '/apps/tickets',
        parentKey: 'apps',
      },
    ],
  },
  {
    key: 'extra-pages',
    icon: 'ri-pages-line',
    label: 'Pages',
    isTitle: true,
    children: [
      {
        key: 'page-starter',
        label: 'Starter',
        url: '/pages/starter',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-timeline',
        label: 'Timeline',
        url: '/pages/timeline',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-sitemap',
        label: 'Sitemap',
        url: '/pages/sitemap',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-invoice',
        label: 'Invoice',
        url: '/pages/invoice',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-faq',
        label: 'FAQs',
        url: '/pages/faqs',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-search-result',
        label: 'Search Results',
        url: '/pages/serach-results',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-pricing',
        label: 'Pricing',
        url: '/pages/pricing',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-maintenance',
        label: 'Maintenance',
        url: '/maintenance',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-coming-soon',
        label: 'Coming Soon',
        url: '/coming-soon',
        parentKey: 'extra-pages',
      },
      {
        key: 'page-gallery',
        label: 'Gallery',
        url: '/pages/gallery',
        parentKey: 'extra-pages',
      },
      {
        key: 'auth',
        label: 'Auth Pages',
        isTitle: false,
        icon: 'ri-shield-user-line',
        collapsed: true,
        children: [
          {
            key: 'auth-login',
            label: 'Log In',
            url: '/auth/login',
            parentKey: 'auth',
          },
          {
            key: 'auth-login-2',
            label: 'Log In 2',
            url: '/auth/login-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-register',
            label: 'Register',
            url: '/auth/register',
            parentKey: 'auth',
          },
          {
            key: 'auth-register-2',
            label: 'Register 2',
            url: '/auth/register-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-signin-signup',
            label: 'Signin-Signup',
            url: '/auth/signin-signup',
            parentKey: 'auth',
          },
          {
            key: 'auth-signin-signup-2',
            label: 'Signin-Signup 2',
            url: '/auth/signin-signup-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-recoverpw',
            label: 'Recover Password',
            url: '/auth/recoverpw',
            parentKey: 'auth',
          },
          {
            key: 'auth-recoverpw-2',
            label: 'Recover Password 2',
            url: '/auth/recoverpw-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-lock-screen',
            label: 'Lock Screen',
            url: '/auth/lock-screen',
            parentKey: 'auth',
          },
          {
            key: 'auth-lock-screen-2',
            label: 'Lock Screen 2',
            url: '/auth/lock-screen-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-logout',
            label: 'Logout',
            url: '/auth/logout',
            parentKey: 'auth',
          },
          {
            key: 'auth-logout-2',
            label: 'Logout 2',
            url: '/auth/logout-2',
            parentKey: 'auth',
          },
          {
            key: 'auth-confirm-mail',
            label: 'Confirm Mail',
            url: '/auth/confirm-mail',
            parentKey: 'auth',
          },
          {
            key: 'auth-confirm-mail-2',
            label: 'Confirm Mail 2',
            url: '/auth/confirm-mail-2',
            parentKey: 'auth',
          },
        ],
      },
      {
        key: 'error-pages',
        label: 'Error Pages',
        isTitle: false,
        icon: 'ri-bug-line',
        parentKey: 'extra-pages',
        collapsed: true,
        children: [
          {
            key: 'page-error-404',
            label: 'Error - 404',
            url: '/pages/404',
            parentKey: 'error-pages',
          },
          {
            key: 'page-error-404-alt',
            label: 'Error - 404-alt',
            url: '/pages/404-alt',
            parentKey: 'error-pages',
          },
          {
            key: 'page-error-500',
            label: 'Error - 500',
            url: '/pages/500',
            parentKey: 'error-pages',
          },
        ],
      },
    ],
  },

  {
    key: 'base-ui',
    icon: 'ri-pencil-ruler-2-line',
    label: 'UI Elements',
    isTitle: true,
    children: [
      {
        key: 'base-ui-avatars',
        label: 'Avatars',
        url: '/ui/avatars',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-buttons',
        label: 'Buttons',
        url: '/ui/buttons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-cards',
        label: 'Cards',
        url: '/ui/cards',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-carousel',
        label: 'Carousel',
        url: '/ui/carousel',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-dropdown',
        label: 'Dropdowns',
        url: '/ui/dropdowns',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-embedvideo',
        label: 'Embed Video',
        url: '/ui/video',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-general',
        label: 'General UI',
        url: '/ui/general',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-grid',
        label: 'Grid',
        url: '/ui/grid',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-images',
        label: 'Images',
        url: '/ui/images',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-list-group',
        label: 'List Group',
        url: '/ui/list-group',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-modals',
        label: 'Modals',
        url: '/ui/modals',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-notifications',
        label: 'Notifications',
        url: '/ui/notifications',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-offcanvas',
        label: 'Offcanvas',
        url: '/ui/offcanvas',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-placeholders',
        label: 'Placeholders',
        url: '/ui/placeholders',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-portlets',
        label: 'Portlets',
        url: '/ui/portlets',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-progress',
        label: 'Progress',
        url: '/ui/progress',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-ribbons',
        label: 'Ribbons',
        url: '/ui/ribbons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-spinners',
        label: 'Spinners',
        url: '/ui/spinners',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tabs-accordions',
        label: 'Tabs & Accordions',
        url: '/ui/tabs-accordions',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tooltips-popovers',
        label: 'Tooltips & Popovers',
        url: '/ui/tooltips-popovers',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-typography',
        label: 'Typography',
        url: '/ui/typography',
        parentKey: 'base-ui',
      },
    ],
  },
  {
    key: 'components',
    icon: 'ri-stack-line',
    label: 'Components',
    isTitle: true,
    children: [
      {
        key: 'extended-ui',
        label: 'Extended UI',
        isTitle: false,
        icon: 'layers',
        badge: { variant: 'info', text: 'Hot' },
        parentKey: 'components',
        collapsed: true,
        children: [
          {
            key: 'extended-ui-range-slider',
            label: 'Range Sliders',
            url: '/extended/range-slider',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-sweet-alert',
            label: 'Sweet Alert',
            url: '/extended/sweet-alert',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-tour',
            label: 'Tour Page',
            url: '/extended/tour',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-scrollspy',
            label: 'Scrollspy',
            url: '/extended/scrollspy',
            parentKey: 'extended-ui',
          },
        ],
      },
      {
        key: 'icons',
        label: 'Icons',
        isTitle: false,
        icon: 'cpu',
        parentKey: 'components',
        collapsed: true,
        children: [
          {
            key: 'icon-feather',
            label: 'Feather',
            url: '/icons/feather',
            parentKey: 'icons',
          },
          {
            key: 'icon-remiix',
            label: 'Remix',
            url: '/icons/remix',
            parentKey: 'icons',
          },
          {
            key: 'icon-boxicons',
            label: 'Boxicons',
            url: '/icons/boxicons',
            parentKey: 'icons',
          },
          {
            key: 'icon-mdiicons',
            label: 'Material Design Icons',
            url: '/icons/mdi',
            parentKey: 'icons',
          },
          {
            key: 'icon-font-awesome',
            label: 'Font Awesome 5',
            url: '/icons/font-awesome',
            parentKey: 'icons',
          },
          {
            key: 'icon-weather',
            label: 'Weather',
            url: '/icons/weather',
            parentKey: 'icons',
          },
        ],
      },
      {
        key: 'forms',
        label: 'Forms',
        isTitle: false,
        icon: 'bookmark',
        parentKey: 'components',
        collapsed: true,
        children: [
          {
            key: 'form-basic',
            label: 'General Elements',
            url: '/forms/elements',
            parentKey: 'forms',
          },
          {
            key: 'form-advanced',
            label: 'Form Advanced',
            url: '/forms/advanced',
            parentKey: 'forms',
          },
          {
            key: 'form-validation',
            label: 'Validation',
            url: '/forms/validation',
            parentKey: 'forms',
          },
          {
            key: 'form-pickers',
            label: 'Pickers',
            url: '/forms/pickers',
            parentKey: 'forms',
          },
          {
            key: 'form-wizard',
            label: 'Wizard',
            url: '/forms/wizard',
            parentKey: 'forms',
          },
          {
            key: 'form-masks',
            label: 'Masks',
            url: '/forms/masks',
            parentKey: 'forms',
          },
          {
            key: 'form-quilljs',
            label: 'Quilljs Editor',
            url: '/forms/quilljs',
            parentKey: 'forms',
          },
          {
            key: 'form-file-uploads',
            label: 'File Uploads',
            url: '/forms/file-uploads',
            parentKey: 'forms',
          },
        ],
      },
      {
        key: 'tables',
        label: 'Tables',
        isTitle: false,
        icon: 'grid',
        parentKey: 'components',
        collapsed: true,
        children: [
          {
            key: 'table-basic',
            label: 'Basic Tables',
            url: '/tables/basic',
            parentKey: 'tables',
          },
          {
            key: 'table-data-table',
            label: 'Data Tables',
            url: '/tables/datatables',
            parentKey: 'tables',
          },
        ],
      },
      {
        key: 'charts',
        label: 'Charts',
        isTitle: false,
        parentKey: 'components',
        icon: 'bar-chart-2',
        collapsed: true,
        children: [
          {
            key: 'chart-apex',
            label: 'Apex Charts',
            url: '/charts/apex',
            parentKey: 'charts',
          },
          {
            key: 'chart-chartjs',
            label: 'Chartjs',
            url: '/charts/chartjs',
            parentKey: 'charts',
          },
        ],
      },
      {
        key: 'maps',
        label: 'Maps',
        isTitle: false,
        icon: 'map',
        parentKey: 'components',
        collapsed: true,
        children: [
          {
            key: 'maps-googlemaps',
            label: 'Google Maps',
            url: '/maps/google',
            parentKey: 'maps',
          },
          {
            key: 'maps-vector',
            label: 'Vector Maps',
            url: '/maps/vector',
            parentKey: 'maps',
          },
        ],
      },
      {
        key: 'multi-level',
        label: 'Multi Level',
        isTitle: false,
        icon: 'ri-share-line',
        collapsed: true,
        children: [
          {
            key: 'second-level',
            label: 'Second Level',
            parentKey: 'multi-level',
            collapsed: true,
            children: [
              {
                key: 'item-1',
                label: 'Item 1',
                parentKey: 'second-level',
              },
              {
                key: 'item-2',
                label: 'Item 2',
                parentKey: 'second-level',
              },
            ],
          },
          {
            key: 'third-level',
            label: 'Third Level',
            parentKey: 'multi-level',
            collapsed: true,
            children: [
              {
                key: 'item-1',
                label: 'Item 1',
                parentKey: 'third-level',
              },
              {
                key: 'item-2',
                label: 'Item 2',
                parentKey: 'third-level',
                collapsed: true,
                children: [
                  {
                    key: 'item-1',
                    label: 'Item 1',
                    parentKey: 'menu-levels-1-1',
                  },
                  {
                    key: 'item-2',
                    label: 'Item 2',
                    parentKey: 'menu-levels-1-1',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    key: 'widgets',
    label: 'Widgets',
    isTitle: false,
    icon: 'ri-honour-line',
    url: '/apps/widgets',
  },
]
