<div class="row">
	<div class="col-sm-3">		
		<div class="listing-info-container card-box m-1 " style="width: 100%;  height: 500px; overflow-y: auto;"></div>	
	</div>	
	<div class="col-sm-3">	
		<div class="listing-gallery card-box m-1" style="width: 100%;  height: 500px"></div>					
	</div>
	<div class="col-sm-3">	
		<div class="card-box m-1">
			<h4 class="m-t-0 mb-2 header-title"><b>Map View</b></h4>
			<div class="gmaps-map" style="width: 100%; height: 435px"></div>			
		</div>	
	</div>	
	<div class="col-sm-3">	
		<div class="card-box m-1">
			<h4 class="m-t-0 mb-2 header-title"><b>Street View</b></h4>
			<div class="gmaps-street" style="width: 100%; height: 435px"></div>			
		</div>						
	</div>
</div>	
<div class="row">
	<div class="col-sm-3">	
		
		<div class="row card-box m-1">
			<div class="col-sm-12">		
				<div class="walkscore-container m-0" style="height: 100px;"></div>	
			</div>
		</div>
		<div class="row card-box m-1">
			<div class="col-sm-12">		
				<div class="csmarkets-container m-0" style="height: 100px;"></div>	
			</div>
		</div>
		<div class="row card-box m-1">
			<div class="col-sm-12">		
				<div class="listing-agents-container m-0" style="height: 200px;"></div>	
			</div>
		</div>

		<div class="row card-box m-1">
				<div class="col-lg-12 widget-chart">	
					<div class="widget-bg-color-icon card-box fadeInDown animated log-container zillow-container zillow-1-container">								
					</div>
				</div>

				<div class="col-lg-12 widget-chart">	
					<div class="widget-bg-color-icon card-box fadeInDown animated log-container zillow-container zillow-2-container">								
					</div>
				</div>
		</div>
	</div>

	<div class="col-sm-3">	
		<div class="row card-box m-1">
				<div class="col-lg-12 widget-chart">	
					<div class="widget-bg-color-icon card-box fadeInDown animated log-container census-container census-1-container">								
					</div>
				</div>

				<div class="col-lg-12 widget-chart">	
					<div class="widget-bg-color-icon card-box fadeInDown animated log-container census-container census-2-container">								
					</div>
				</div>
		</div>		
	</div>
	<div class="col-sm-3">
		<div class="card-box m-1">	
					<a href="#" class="btn btn-sm btn-primary pull-right gmaps-map-oa-a">Analyze Map Homes</a>		
					<div class="gmaps-map-oa-summary"></div>					
					<div class="gmaps-map-oa-list"></div>		
		</div>
	</div>
	<div class="col-sm-3">	
		<div class="card-box m-1">	
					<a href="#" class="btn btn-sm btn-primary pull-right gmaps-map-places-a">Analyze Map Businesses</a>		
					<div class="gmaps-map-places-summary"></div>					
					<div class="gmaps-map-places-list"></div>		
				</div>
	</div>
</div>	
