<?php
?>
<form>    
    <input type="hidden" name="action" value="searchContractors">    
    <div class="row">
        <div class="col-sm-6">                        
            <div class="form-group">
                <label>Query</label>
                <input type="text" class="form-control" name="q">
            </div>
        </div>
        <div class="col-sm-2">                        
            <div class="form-group">
                <label>Zip</label>
                <input type="text" class="form-control" name="zip" palceholder="">
            </div>
        </div>  
        <div class="col-sm-2">                        
            <div class="form-group">
                <label class="control-label w-100">&nbsp;</label>
                <a href="#" class="btn btn-primary"><i class="fa fa-search"></i> Search</a>
            </div>
        </div>                
    </div>        
</form>
