<style>.select2.select2-container{ width: 100%!important; }</style>

<div class="row">
	<div class="col-sm-4">
		<div class="folders card-box mb-1">  
			<a href="#" class="btn btn-outline-primary btn-sm pull-right mr-2 main-status-edit"><i class="fa fa-edit"></i> Edit Status</a>
			<h4 class="m-t-0 mb-4 header-title"><b>Deal Status</b></h4>
			<hr>
			<h1 class="deal-main-status text-center">No Status</h1> 						
		</div>	

		<div class="folders card-box mb-1">  
			<h4 class="m-t-0 mb-2 header-title"><b>Folders</b></h4>  
			<div class="form-group">
				<input type="text" class="form-control folder-search" placeholder="Search folders/files...">
			</div>			
			<div class="folders-tree"></div>			
		</div>	

		<div class="card-box m-0 w-100 height-400 mb-1">						
			<a href="#" class="btn btn-outline-primary btn-sm pull-right mr-2 todo-add"><i class="fa fa-plus"></i> Create Task</a> 							
			<a href="#" class="pull-right mr-2 todo-show-closed-a text-muted">Show completed tasks</a> 							
			<h4 class="m-t-0 mb-4 header-title"><b>Todo Tasks</b></h4>
			<hr>
			<div class="inbox-widget h-100">
				<div class="todo-container">
				</div>
			</div>
		</div>
											
	</div>
	<div class="col-sm-6">		
		<div class="card-box m-0 w-100 height-400 mb-1">			
			<a href="#" class="btn btn-outline-primary btn-sm pull-right mr-2 updates-add"><i class="fa fa-plus"></i> Post New Update</a> 							
			<h4 class="m-t-0 mb-4 header-title"><b>Updates/Notes</b></h4>	
			<hr>
			<form class="updates-search-form">
				<input type="hidden" name="action" value="loadUpdates"/>
			<div class="row">
				<div class="col-sm-5">
					<div class="form-group">
						<label>Query</label>
						<input type="text" name="filter[q]" class="form-control" palceholder="Search title or description..."/>
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">						
						<label>Type</label>
						<select name="filter[type][]" class="form-control select2" placeholder="All Types" multiple>							
							<? foreach(getUpdatesTypes() as $t): ?>
							<option value="<?=$t?>"><?=$t?></option>
							<? endforeach; ?>
						</select>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="form-group">
						<label>Todo Task</label>
						<select name="filter[todo_id]" class="form-control">
							<option value="">All tasks</option>
							<? foreach(getDealTasks($_GET['id']) as $t): ?>
							<option value="<?=$t->id?>"><?=$t->title?></option>
							<? endforeach; ?>
						</select>						
					</div>
				</div>
				<div class="col-sm-2">
					<div class="form-group">						
						<label>&nbsp;</label><br>
						<a href="#" class="btn btn-sm btn-primary updates-search-a"><i class="fa fa-search"></i> Search</a>
					</div>
				</div>
			</div>
			</form>		

			<div class="inbox-widget h-100 overflow-y-auto" style="background:#f5f5f5; padding: 20px; margin-top: 20px;">
				<div class="timeline updates-container">
				</div>
			</div>
		</div>
	</div>

</div>


<script id="template-todo-item" type="x-handlebars">
{{#each items}}
<div class="todo-item {{#xIf closed '==' '1'}}todo-closed hidden{{/xIf}}" data-id="{{id}}">
	<div class="float-right">
		<button class="btn btn-icon btn-sm waves-effect waves-light btn-outline-secondary m-b-5 todo-edit-a"> <i class="fa fa-edit"></i> </button>
		<button class="btn btn-icon btn-sm waves-effect waves-light btn-outline-primary m-b-5 todo-update-a"> <i class="fa fa-plus"></i> </button>
	</div>
    <div class="checkbox checkbox-primary">			
        <input id="todocheckbox{{id}}" type="checkbox" class=" pointer" {{#xIf closed '==' '1'}}checked{{/xIf}}>		
        <label for="todocheckbox{{id}}" class=" pointer"><h4 class="todo-title">{{title}}</h4></label>		 	
    </div>	
	{{#each tags}}<div class="badge badge-sm badge-secondary mr-2">{{this}}</div>{{/each}}
	<p>{{description}}</p>	
	{{#if lastUpdate.id}}	
		</i> <h5>Latest Update <div class="badge badge-sm badge-primary">{{lastUpdate.timestamp_ago}}</div></h5>
		{{lastUpdate.title}} - By <div class="badge badge-sm badge-secondary">{{lastUpdate.user.username}}</div>
		<p>{{lastUpdate.description}}</p>
	{{/if}}
	{{#unless @last}}<hr>{{/unless}}	
</div>
{{else}}
No tasks found!
{{/each}}                       
</script>


<script id="template-updates-uploader-preview-item" type="x-handlebars">
<div class="fileupload-preview-item">
    <a href="#" class="fileupload-preview-item-remove text-danger"><i class="fa fa-times"></i></a>    
    <img src="{{url}}" class="border-radius-lg">        
    <div class="text-xs text-truncate">{{name}}</div>
</div>
</script>
<script id="template-updates-item" type="x-handlebars">
{{#each items}}	
<article class="timeline-item {{#isEven @index}}alt{{else}}{{/isEven}} updates-item" data-id="{{id}}">
	<div class="timeline-desk">
		<div class="panel">
			<div class="panel-body">
				<span class="{{#isEven @index}}arrow-alt{{else}}arrow{{/isEven}}"></span>
				<span class="timeline-icon"></span>
				<div class=" badge badge-sm badge-primary pull-{{#isEven @index}}left{{else}}right{{/isEven}}">{{timestamp_ago}}</div>
				<h4>{{title}}</h4>
				<div class="text-bold text-sm text-{{#isEven @index}}right{{else}}left{{/isEven}}"><i class="fa fa-user"></i> {{user.username}}</div>
				{{#xIf todo_id ">" "0"}}<div class="text-bold text-sm text-{{#isEven @index}}right{{else}}left{{/isEven}}">Todo Task: {{todo.title}}</div>{{/xIf}}
				<p class="timeline-date text-muted"><small>{{timestamp}}</small></p>				
				<p>{{desc}}</p>
				<div class="badge badge-sm badge-secondary pull-{{#isEven @index}}right{{else}}left{{/isEven}}">{{type}}</div>
				<div class="album">
				{{#each files}}  
				<div class="row">
					<div class="col-sm-12">				
						<a href="<?=$GLOBALS['system']['upload_href']?>/{{href}}" target="_blank">
							<img alt="" src="{{icon}}">
							<span class="text-sm">{{filename}}</span>
						</a>
					</div>
					{{#if @last}}{{else}}<div class="col-sm-12"><hr></div>{{/if}}					
				</div>				
				{{/each}}
                </div>
            	<div class="clearfix"></div>
			</div>
		</div>
	</div>
</article>
{{/each}}
</script>
