<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?=$pagedata['title']." - ".$GLOBALS['site']['title']?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />        
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <link rel="shortcut icon" href="assets/images/favicon.ico">
 
        <script src="<?=$GLOBALS['system']['theme_base']?>/js/modernizr.min.js"></script>
    </head>
<body>

<!-- --------------------------- CSS Defaults ---------------------------  -->
<link href="<?=$GLOBALS['system']['theme_base']?>../../plugins/morris/morris.css" rel="stylesheet">
<link href="<?=$GLOBALS['system']['theme_base']?>/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="<?=$GLOBALS['system']['theme_base']?>/css/icons.css" rel="stylesheet" type="text/css" />
<link href="<?=$GLOBALS['system']['theme_base']?>/css/style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

<!-- --------------------------- CSS Libs ---------------------------  -->
<!-- Toastr style -->
<link href="/css/lib/toastr/toastr.min.css" rel="stylesheet">
<link href="/js/lib/bootstrap-tagsinput/dist/bootstrap-tagsinput.css" rel="stylesheet" />

<!-- Data Tables -->
<link href="/css/lib/dataTables/dataTables.bootstrap4.min.css" rel="stylesheet">
<link href="/css/lib/dataTables/dataTables.responsive.css" rel="stylesheet">
<link href="/css/lib/dataTables/dataTables.tableTools.min.css" rel="stylesheet">

<link href="/css/lib/switchery/switchery.css" rel="stylesheet">

<link href="/css/lib/datepicker/datepicker3.css" rel="stylesheet">
<link href="/css/lib/daterangepicker/daterangepicker-bs3.css" rel="stylesheet">

<link href="/css/lib/jasny/jasny-bootstrap.min.css" rel="stylesheet">

<link href="/js/lib/gridstack/gridstack.css" rel="stylesheet">
<link href="/js/lib/jQuery-QueryBuilder/dist/css/query-builder.default.css" rel="stylesheet">

<link href="/css/lib/select2/select2.min.css" rel="stylesheet">
<link href="<?=$GLOBALS['system']['theme_base']?>../../plugins/jquery-circliful/css/jquery.circliful.css" rel="stylesheet">

<link href="/js/lib/sortable/sortable.css" rel="stylesheet">

<link href="/js/lib/jstree/style.min.css" rel="stylesheet">
<link href="/js/lib/jstree/themes/default/style.min.css" rel="stylesheet">

<link href="/js/lib/ion-rangeslider/ion.rangeSlider.css" rel="stylesheet">
<link href="/js/lib/ion-rangeslider/ion.rangeSlider.skinFlat.css" rel="stylesheet">


<link type="text/css" href="<?=$GLOBALS['system']['theme_base']?>../../plugins/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet">

<link href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css" rel="stylesheet">


<!-- --------------------------- CSS Custom ---------------------------  -->
<link href="/css/style.css" rel="stylesheet">
<link href="/css/site.less?<?=filemtime($GLOBALS['system']['path'].'/css/site.less')?>" rel="stylesheet/less" type="text/css"/>
