<div class="wrapper-page">
	<div class="text-center">
		<a href="#" class="logo-lg"><i class="mdi mdi-radar"></i> <span><?=$GLOBALS['site']['title']?></span> </a>
	</div>
	

	
	
<form class="form-horizontal m-t-20" method="post" novalidate>
	<input type="hidden" name="process" value="1" />
	<? if($error): ?><div class="alert alert-danger"><?=$error?></div><? endif; ?>
	
	<div class="login-container">
		<div class="form-group row">
			<div class="col-12">
				<div class="input-group">
					<span class="input-group-addon"><i class="mdi mdi-account"></i></span>
					<input class="form-control" name="crm_username" type="text" placeholder="Username">
				</div>
			</div>
		</div>
	
		<div class="form-group row">
			<div class="col-12">
				<div class="input-group">
					<span class="input-group-addon"><i class="mdi mdi-radar"></i></span>
					<input class="form-control" type="password" name="crm_password" placeholder="Password">
				</div>
			</div>
		</div>
	
		<div class="form-group text-right m-t-20">
			<div class="col-xs-12">
				<button class="btn btn-primary btn-custom w-md waves-effect waves-light" onclick="javascript: $('.form').submit()" type="submit">Log In</button>
			</div>
		</div>
	
	</div>
	
	<div class="reset-password-container" style="display: none">
				<div class="ibox-content">
					<h2 class="font-bold">Forgot password</h2>
					<p>Enter your username and your password will be emailed to you.</p>
					<div class="row">
						<div class="col-lg-12">
							<form class="m-t" role="form" method="post">
								<input type="hidden" name="resetPassword" value="1" />
								<div class="form-group"><input type="text" class="form-control" placeholder="Username" required=""></div>
								<button type="submit" class="btn btn-primary block full-width m-b">Send password</button>
							</form>					
	                    </div>
	                </div>
	            </div>
	</div>
	       
</form>
</div>
