<?php 
$struct = '{
	"Name":{"crexi.com":"Name"},{"commercialexchange.com":""},
	"Description":{"crexi.com":"Description"},{"commercialexchange.com":""},
	"Price":{"crexi.com":"AskingPrice"},{"commercialexchange.com":""},
	"Address":{"crexi.com":"Locations/0/Address"},{"commercialexchange.com":""},
	"City":{"crexi.com":"Locations/0/City"},{"commercialexchange.com":""},
	"State":{"crexi.com":"Locations/0/State"},{"commercialexchange.com":""},
	"Zip":{"crexi.com":"Locations/0/Zip"},{"commercialexchange.com":""},
	"Square Ft.":{"crexi.com":"Details/Square Footage"},{"commercialexchange.com":""},
	"Lot":{"crexi.com":"Details/Lot Size (acres)"},{"commercialexchange.com":""},
	"Broker First Name":{"crexi.com":"broker/0/FirstName"},{"commercialexchange.com":""},
	"Broker Last Name":{"crexi.com":"broker/0/LatName"},{"commercialexchange.com":""},
}';
?>