<? 
    $types = [];
    $q = mysql_query("SELECT DISTINCT type FROM filters2 ORDER BY type ASC");
    while(list($r) = mysql_fetch_array($q)) $types[] = $r;
?>
<form class="filter-search-form">
    <input type="hidden" name="action" value="searchFilters">
    <div class="row">
        <div class="col-sm-2">
            <div class="form-group">
                <label>User</label>
                <select class="form-control" name="user_id">
                    <option value="">All users...</option>
                    <? foreach(Users::getActiveUsers() as $u): ?>
                        <option value="<?=$u->id?>"><?=$u->username?></option>
                    <?endforeach;?>
                </select>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label>Type</label>
                <select class="form-control" name="type">
                    <option value="">All types...</option>
                    <? foreach($types as $t): ?>
                        <option value="<?=$t?>"><?=ucwords($t)?></option>
                    <?endforeach;?>
                </select>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" name="q" placeholder="search title..."/>
            </div>
        </div>
        <div class="col-sm-2">
            <div class="form-group">
                <label class="form-label">&nbsp;</label>
                <a href="#" class="btn btn-primary filter-search-a mt-4"><i class="fa fa-search"></i> Search</a>
            </div>
        </div>
    </div>
</form>
<div class="row mt-3">
    <div class="col-sm-12">
        <h4>Matching Filters</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>                    
                    <th>User</th>
                    <th>Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="filter-search-res">
            </tbody>
        </table>        
    </div>
    <div class="col-sm-6">
        <h4>Filter Preview</h4>
        <div class=" filter-search-res-view-container"></div>
    </div>
</div>