<div class="page-agents">		
	<div class="row card-box">
        <div class="col-lg-12">
            <div class="ibox-content m-b-sm "> 
            	<a href="#" class="btn btn-primary pull-right create-a"><i class="fa fa-plus"></i> Add New User</a>      
            	<h3>Team Members</h3>   
            	<hr>                      
				
				<table class="table">
						<thead class="bg-gray">
						<tr>
							<th class="center" style="width: 1%">ID</th>
							<th>Username</th>
							<th>Name</th>													
							<th>Type</th>													
							<th>Status</th>													
							<th class="center">Last Login</th>							
							<th class="text-center"></th>
						</tr>
						</thead>
						<tbody>
						<? foreach($agents as $agent): ?>
							<tr class="agent-item selectable <?=($agent->status>0)?'':'disabled'?>" data-id="<?=$agent->id?>">
								<td class="center"><?=$agent->id?></td>
								<td><?=$agent->username?></td>
								<td><?=$agent->first_name?> <?=$agent->last_name?></td>
								<td><?=$agent->type?></td>
								<td><div class="badge badge-<?=($agent->status)?'success':'danger'?>"><?=($agent->status)?'Active':'Inactive'?></div></td>
								<td class="center"><?=$agent->last_login?></td>								
								<td class="text-right actions">
									<div class="btn-group btn-group-sm">										
										<a href="#" class="edit-a btn btn-xs btn-primary mr-2"><i class="fa fa-pencil"></i></a>
										<a href="#" class="remove-a btn btn-xs btn-danger"><i class="fa fa-trash"></i></a>
									</div>
								</td>
							</tr>
						<? endforeach; ?>						
						</tbody>
				</table>					
            </div>
        </div>
    </div>
</div>



