<?php
	if($_REQUEST['templateData']){
		
	}				
?>
<form>																
	<input type="hidden" name="action" value="searchNumber"/>					
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
				<label class="strong">Area Code</label>
				<input type="text" class="form-control" name="areacode" value="" required>
			</div>
			<div class="form-group">
				<a href="#" class="btn btn-block btn-primary dialpad-buy-search-a"><i class="fa fa-search"></i> Search</a>
			</div>												
		</div>	
	</div>			
    <div class="row">
        <div class="dialpad-buy-search-res text-center col-sm-12"></div>
    </div>			
</form>	