<div class="row">	
	<div class="col-sm-12 text-center">
		<a href="#" data-text-off="Mute" data-text-on="Unmute" data-icon-off="fa-microphone-slash" data-icon-on="fa-microphone" data-class-on="btn-secondary" data-class-off="btn-outline-secondary" class="btn btn-sm btn-outline-secondary dialpad-mute-a">
			<i class="fa fa-microphone-slash"></i><label class="mb-0 ml-1 pointer">Mute</label>
		</a>

		<a href="#" data-text-off="Start Recording" data-text-on="Pause Recording" data-icon-off="fa-play" data-icon-on="fa-pause" data-class-on="btn-danger" data-class-off="btn-outline-danger" class="btn btn-sm btn-outline-danger dialpad-record-a hidden">
			<i class="fa fa-play"></i><label class="mb-0 ml-1 pointer">Start Recording</label>
		</a>

	</div>
	
	<!--
	<a href="javascript:;" class="col-xs-3 text-center text-success dlr-ctrl-btn">
		<i class="fa fa-volume-up f-s-18"></i>
		<p class="m-0">speaker</p>
	</a>
	
	<a href="javascript:;" class="col-xs-3 text-center text-muted dlr-ctrl-btn">
		<i class="fa fa-dot-circle-o f-s-18"></i>
		<p class="m-0">record</p>
	</a>
	
	<a href="javascript:;" class="col-xs-3 text-center text-muted dlr-ctrl-btn">
		<i class="fa fa-pause f-s-18"></i>
		<p class="m-0">hold</p>
	</a>
	-->
</div><!--/.row-->