<div class="row m-0 keypad-wrapper dialpad">
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="1">
            <h3 class="m-t-0 m-b-5">1</h3>
            <p class="m-0">&nbsp;</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="2">
            <h3 class="m-t-0 m-b-5">2</h3>
            <p class="m-0">ABC</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-right-1 border-top-1 dial-digit" data-digit="3">
            <h3 class="m-t-0 m-b-5">3</h3>
            <p class="m-0">DEF</p>
        </a><!--/.col 4-->
    </div>

    <div class="row m-0 keypad-wrapper dialpad">
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="4">
            <h3 class="m-t-0 m-b-5">4</h3>
            <p class="m-0">GHI</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="5">
            <h3 class="m-t-0 m-b-5">5</h3>
            <p class="m-0">JKL</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-right-1 border-top-1 dial-digit" data-digit="6">
            <h3 class="m-t-0 m-b-5">6</h3>
            <p class="m-0">MNO</p>
        </a><!--/.col 4-->
    </div><!--/.keypad-wrapper-->

    <div class="row m-0 keypad-wrapper dialpad">
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="7">
            <h3 class="m-t-0 m-b-5">7</h3>
            <p class="m-0">PQRS</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 dial-digit" data-digit="8">
            <h3 class="m-t-0 m-b-5">8</h3>
            <p class="m-0">TUV</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-right-1 border-top-1 dial-digit" data-digit="9">
            <h3 class="m-t-0 m-b-5">9</h3>
            <p class="m-0">WXYZ</p>
        </a><!--/.col 4-->
    </div><!--/.keypad-wrapper-->

    <div class="row m-0 keypad-wrapper dialpad">
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 border-bottom-1 dial-digit" data-digit="*">
            <h3 class="m-t-0 m-b-5">*</h3>
            <p class="m-0">&nbsp;</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-top-1 border-bottom-1 dial-digit" data-digit="0">
            <h3 class="m-t-0 m-b-5">0</h3>
            <p class="m-0">+</p>
        </a><!--/.col 4-->
        <a href="javascript:;" class="dialer-key col-sm-4 border-left-1 border-right-1 border-top-1 border-bottom-1 dial-digit" data-digit="#">
            <h3 class="m-t-0 m-b-5">#</h3>
            <p class="m-0">&nbsp;</p>
        </a><!--/.col 4-->
    </div><!--/.keypad-wrapper-->