<div class="theme-panel-content dialpad-panel" style="display: none;" data-type="incoming">
  		<h5 class="text-center f-s-18 m-t-20 from-label">{{formatPhoneNumber parameters.From}}</h5>
        <div class="callerId-container text-center"></div>
        
        <div class="caller-dp text-center m-b-10">

        <button class="pulsate" style="font-size: 63px; background: white; border: 0; border-radius: 50%; padding: 0px 23px; margin: 16px 0;"> <i class="fa fa-phone"></i> </button>
        
        </div><!--/.caller-dp-->
        
        <p class="text-center f-s-14 m-b-20">Incoming Call</p>
        <div class="row m-b-20">
        	<div class="col-sm-6">
            	<button class="btn btn-success btn-block dialpad-accept-a"><i class="fa fa-phone"></i></button>
            </div><!--/.col 6-->
            <div class="col-sm-6">
            	<button class="btn btn-danger btn-block dialpad-reject-a"><i class="fa fa-phone"></i></button>
            </div><!--/.col 6-->
        </div><!--./row-->
		
    </div><!--/.incoming call content-->