<!-- call in progress content -->
	<div class="theme-panel-content dialpad-panel" style="display: none" data-type="incall">
        {{#xIf _direction '==' 'OUTGOING'}}
  		    <h5 class="text-center f-s-18 m-t-20 to-label">Outbound call connected to:</h5>
            <div class="callerId-container text-center">{{formatPhoneNumber customParameters.To}}</div>
        {{else}}
            <h5 class="text-center f-s-18 m-t-20 to-label">Incoming call from:</h5>
            <div class="callerId-container text-center">{{formatPhoneNumber parameters.From}}</div>
        {{/xIf}}
        
        <div class="caller-dp text-center m-b-10"><hr></div><!--/.caller-dp-->
        
        <p class="text-center f-s-14 m-b-20"><span class="dialpad-timer">00:00:00</span></p>


        <?=includeTemplate('widgets::dialer::_dialpad_buttons');?>

        <div class="row m-b-20">
            <div class="col-sm-12">
                <button class="btn btn-danger btn-block dialpad-hangup-a"><i class="fa fa-phone"></i></button>
            </div><!--/.col 12-->
        </div><!--./row-->        
        
        <?=includeTemplate('widgets::dialer::_call_actions');?>
    </div><!-- /.call in progress content -->