<style>
.wrap>.container{ width: 90%!important; max-width: 90%!important; }
h3{ margin-top: 0!important; }

.arenderjson				   { background: black; }
.arenderjson a              { text-decoration: none; }
.arenderjson .disclosure    { color: crimson;
                             font-size: 150%; }
.arenderjson .syntax        { color: grey; }
.arenderjson .string        { color: red; }
.arenderjson .number        { color: cyan; }
.arenderjson .boolean       { color: plum; }
.arenderjson .key           { color: #428bca; }
.arenderjson .keyword       { color: lightgoldenrodyellow; }
.arenderjson .object.syntax { color: lightseagreen; }
.arenderjson .array.syntax  { color: lightsalmon; }

</style>
<div class="page-listings">	
	<div class="row card-box">
		<div class="col-sm-12">
			<div class="ibox-content m-b-sm border-bottom">
				<h3>Filters</h3>   
            	<hr>  
				
				<form class="search-form">
				<input type="hidden" name="action" value="loadListings">
				<div class="row">								
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Title</label>
							<input type="text" class="form-control" name="filter[title]" value="">						
						</div>
					</div>						
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Scrape Date</label>
							<input type="text" class="form-control daterangepicker" data-type="advanced" name="filter[date]">						
						</div>
					</div>	
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Source</label>
							<select class="form-control"  name="filter[source]">
								<option value="">All</option>
								<option value="crexi.com">crexi.com</option>
								<option value="commercialexchange.com">commercialexchange.com</option>			
								<option value="century21.com">century21.com</option>
							</select>												
						</div>
					</div>	
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Status</label>
							<select class="form-control"  name="filter[status]">
								<option value="">All</option>
								<option value="pending">Pending</option>
								<option value="ready">Ready</option>
								<option value="error">Error</option>
							</select>												
						</div>
					</div>		
				</div>
				<div class="row">	
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">Last Update Date</label>
							<input type="text" class="form-control daterangepicker" data-type="advanced" name="filter[update_date]">						
						</div>
					</div>	
					<div class="col-sm-3">
						<div class="form-group">
							<label>Path</label>				
							<input type="text" class="form-control" name="filter[update_path]" placeholder="Ex: /sale/price OR /price/">										
						</div>
					</div>			
					<div class="col-sm-3">
						<div class="form-group">
							<label class="control-label">&nbsp;</label>
							<a href="#" class="btn btn-block btn-primary search-a"><i class="fa fa-search"></i> Search</a>
						</div>
					</div>				
				</div>
				</form>
			</div>
		</div>
	</div>	
	
	<div class="row card-box">
        <div class="col-lg-12">
			<div class="ibox-content m-b-sm">
				<div class="row"><div class="col-lg-12"><h3>Listings Stats</h3><hr></div></div>
				<div class="row summary-container">																
				</div>
			</div>
		</div>
	</div>	
	
	<div class="row card-box">
        <div class="col-lg-12">
            <div class="ibox-content m-b-sm "> 
            	<a href="#" class="btn btn-primary pull-right export-a"><i class="fa fa-download"></i> Export Results</a>      
            	<h3>Listings</h3>   
            	<hr>                      
				<table class="table listings-container">
                        <thead>
                            <tr>																								
								<th data-orderable="true">Title</th>
								<th data-orderable="true">Status</th>								
								<th data-orderable="true">Source</th>
								<th data-orderable="true" data-default-sort="desc">Date Created</th>
								<th data-orderable="false">Score</th>																							
								<th data-orderable="false"># Images</th>																
								<th data-orderable="false"># Updates</th>
								<th data-orderable="false">Last Seen</th>
								<th data-orderable="false"></th>																								
                            </tr>
                        </thead>
                        <tbody>	                        				
                        </tbody>
				</table>                
            </div>
        </div>
    </div>
		
	<script id="template-summary" type="x-handlebars">	
		{{#each stats.scrapes}}	
		<div class="col-lg-6 m-b-30">				
			<h5 class="m-b-0">{{@key}}</h5>
			<div class="row">
			{{#each this}}								
				<div class="col-sm-3">
					<div class="text-muted font-16">{{@key}}</div>
					<h4 class="mb-0">{{this}}</h4>						
				</div> 					                                     																	
			{{/each}}
			</div>
		</div>	
		{{/each}}	
	</script>
	
	
	<script id="template-updates-item" type="x-handlebars">
		<tr data-id="{{id}}" data-listing-id="{{remote_id}}" class="updates-item">
			<td>{{timestamp}}</td>
			<td>{{operation}}</td>			
			<td nowrap><small>{{path}}</small></td>							
			<td>{{value_old}}</td>
			<td>{{value_new}}</td>																								
			<td class="text-right" nowrap>																
			</td>
		</tr>
	</script>
	
	<script id="template-listings-item" type="x-handlebars">
		<tr data-id="{{id}}" data-remote-id="{{remote_id}}" class="listings-item">
			<td><a href="{{url}}" target="_blank">{{title}}</a></td>			
			<td>{{status}}</td>							
			<td>{{source}}</td>
			<td nowrap>{{timestamp}}</td>
			<td>
				{{#if score}}
					{{#if score.locationScore}}
						{{score.locationScore}}
					{{else}}
						0
					{{/if}}
					<a href="#" class="btn btn-xs btn-primary score-a" title="View Details" data-lng="{{lng}}" data-lat="{{lat}}"><i class="fa fa-eye"></i></a>
				{{else}}
					-
				{{/if}}
			</td>																						
			<td>{{images_count}}</td>																					
			<td>{{updates_count}}</td>
			<td>{{last_seen_ago}}</td>
			<td class="text-right" nowrap>
				<a href="#" class="btn btn-sm btn-primary updates-a" title="View Updates"><i class="fa fa-bar-chart-o"></i></a>
				<a href="#" class="btn btn-sm btn-info view-a" title="View Details"><i class="fa fa-eye"></i></a>														
			</td>
		</tr>
	</script>
	<script id="template-empty" type="x-handlebars">
		<tr>
			<td>No cards found!</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>			
			<td></td>			
			<td></td>			
			<td></td>			
		</tr>
	</script>
</div>


