<form>
    <input type="hidden" name="action" value="updateStatus"/>
    <input type="hidden" name="id" value="{{id}}"/>

    <div class="form-group">
        <label class="form-label">Status</label>
		<selectadd key="deals_data.status" name="status" theme="primary" default-value="" placeholder="Select a status, or create a new one..." class="required">      		   
	</div>						            
</form>