<div class="grid-stack">
</div>
<div class="grid-box card-box listing-info-container"></div>
<div class="grid-box card-box gmaps-map" style="width: 100%; height: 500px"></div>											
<div class="grid-box card-box gmaps-street" style="width: 100%;  height: 500px"></div>			
<div class="grid-box card-box widget-bg-color-icon card-box fadeInDown animated log-container zillow-container zillow-1-container"></div>
<div class="grid-box card-box widget-bg-color-icon card-box fadeInDown animated log-container zillow-container zillow-2-container"></div>
<div class="grid-box card-box">	
	<a href="#" class="btn btn-sm btn-primary pull-right gmaps-map-oa-a">Analyze Map Homes</a>		
	<div class="gmaps-map-oa-summary"></div>					
	<div class="gmaps-map-oa-list"></div>
</div>
<div class="grid-box card-box widget-bg-color-icon card-box fadeInDown animated log-container census-container census-1-container"></div>				
<div class="grid-box card-box widget-bg-color-icon card-box fadeInDown animated log-container census-container census-2-container"></div>				
<div class="grid-box card-box">	
	<a href="#" class="btn btn-sm btn-primary pull-right gmaps-map-places-a">Analyze Map Businesses</a>		
	<div class="gmaps-map-places-summary"></div>					
	<div class="gmaps-map-places-list"></div>
</div>