<?php
    $twilio = new Twilio();
    $id = $_REQUEST['templateData']['id'];
    
    $number = $twilio->getNumber($id);    
    $types = Users::getTypes();        
?>
<form>																
	<input type="hidden" name="action" value="assignNumber"/>					
    <input type="hidden" name="id" value="{{id}}"/>					
	<div class="row">
		<div class="col-sm-12">
			<div class="form-group">
				<label class="strong">User Type:</label>
                <select class="form-control" name="type_id">
                    <option value="">Not Assigned</option>
					<? foreach($types as $t): ?>
					<option value="<?=$t->id?>" <?=($t->id==$number->assigned_type->type_id)?'selected':''?>><?=$t->title?></option>
					<? endforeach; ?>
				</select>							
			</div>			
		</div>	
	</div>			    
</form>	