<?php    
    $id = $_REQUEST['templateData']['id'];
    $contact = $ct->loadDealContact($id); 
    
    if($contact->entries){
        $phones = array_filter($contact->entries,function($obj){ return $obj->type == 'phone';});        
        $phone = array_pop($phones)->value;
        $phone2 = array_pop($phones)->value;
        $email = reset(array_filter($contact->entries,function($obj){ return $obj->type == 'email';}))->value;
    }
?>
<form>    
    <input type="hidden" name="action" value="contactCreate">        
    <input type="hidden" name="id" value="{{id}}">    
    <div class="row">         
        <div class="col-sm-12"> 
            <div class="form-group select-input">
				<label class="strong">Type *</label>
				<select class="form-control" required>
					<option value="">Select...</option>
					<option value="new">Create a new type...</option>
					<option disabled>──────────</option>
					<? foreach(getContactsTypes() as $s): ?>
						<option value="<?=$s?>" <?=($s==$contact->type)?'selected':''?>><?=$s?></option>
					<? endforeach; ?>
				</select>
				<div class="row select-input-value hidden">
					<div class="col-sm-10">
						<input type="text" class="form-control" name="type" value="<?=$contact->type?>" required>
					</div>
					<div class="col-sm-2">
						<a href="#" class="btn btn-danger select-input-cancel"><i class="fa fa-times"></i></a>
					</div>
				</div>
			</div>				            
        </div> 
        <div class="col-sm-12"> 
            <div class="form-group select-input">
				<label class="strong">Sub Type</label>
				<select class="form-control" required>
					<option value="">Select...</option>
					<option value="new">Create a new type...</option>
					<option disabled>──────────</option>
					<? foreach(getContactsSubtypes() as $s): ?>
						<option value="<?=$s?>" <?=($s==$contact->subtype)?'selected':''?>><?=$s?></option>
					<? endforeach; ?>
				</select>
				<div class="row select-input-value hidden">
					<div class="col-sm-10">
						<input type="text" class="form-control" name="subtype" value="<?=$contact->type?>">
					</div>
					<div class="col-sm-2">
						<a href="#" class="btn btn-danger select-input-cancel"><i class="fa fa-times"></i></a>
					</div>
				</div>
			</div>				            
        </div>
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Name *</label>
                <input type="text" class="form-control" name="name" value="<?=$contact->name?>" required>
            </div>
        </div>
        <div class="col-sm-12"><hr></div>
        <div class="col-sm-12">                 
            <div class="form-group">
                <label>Phone</label>
                <div class="input-group mb">
                    <input type="text" name="phone" class="form-control" value="<?=$phone?>">
                    <div class="input-group-append"><button class="btn btn-outline-secondary contacts-create-lookup-a" type="button">Lookup</button></div>
                </div>
            </div>
        </div>         
        <div class="col-sm-12">                                    
            <div class="form-group">
                <label>Alt. Phone</label>
                <input type="text" class="form-control" name="phone2" value="<?=$phone2?>">
            </div>
        </div> 
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Email</label>
                <input type="text" class="form-control" name="email" value="<?=$email?>">
            </div>
        </div> 

        <div class="col-sm-12"><hr></div>
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Company</label>
                <input type="text" class="form-control" name="company" value="<?=$contact->company?>">
            </div>
        </div> 
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Website</label>
                <input type="text" class="form-control" name="website" value="<?=$contact->website?>">
            </div>
        </div> 
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Address</label>
                <input type="text" class="form-control" name="address" value="<?=$contact->address?>">
            </div>
        </div> 
        <div class="col-sm-6">                        
            <div class="form-group">
                <label>City</label>
                <input type="text" class="form-control" name="city" value="<?=pick($contact->city,$deal->standerized->city)?>">
            </div>
        </div> 
        <div class="col-sm-3">                        
            <div class="form-group">
                <label>State</label>
                <select class="form-control" name="state">
                    <option value="">Select...</option
                    <? foreach(array_keys($GLOBALS["states"]) as $k): ?>
                    <option value="<?=$k?>" <?=(in_array($k,[$contact->state,$deal->standerized->state]))?'selected':''?>><?=$k?></option>
                    <? endforeach; ?>
                </select>
            </div>
        </div> 
        <div class="col-sm-3">                        
            <div class="form-group">
                <label>Zip</label>
                <input type="text" class="form-control" name="zip" value="<?=pick($contact->zip,$deal->standerized->zip)?>">
            </div>
        </div> 
        <div class="col-sm-12"><hr></div>
        <div class="col-sm-12">                        
            <div class="form-group">
                <label>Notes</label>
                <textarea class="form-control" rows="6" name="notes" palceholder=""><?=$contact->data->notes?></textarea>
            </div>
        </div>          
    </div>        
</form>
