<div class="row">
    <div class="col-sm-4 convo-details-container">
        
    </div>
    <div class="col-sm-8">        
        <div class="convo-container">                            
        </div>  
        <div class="convo-send-container">
            <div class="d-flex">
                <div class="mr-2" style="flex-grow: 1;">
                    <textarea rows="3" class="form-control convo-sms-body" placeholder="Type your message..."></textarea>
                    <div class="w-100 text-right"><span class="convo-sms-counter">0</span>/1600</div>
                </div>
                <a href="#" class="btn btn-primary pt-4 convo-sms-a" style="margin-bottom: 22px;"><i class="fa fa-send"></i> Send SMS</a>
            </div>          
        </div>  
    </div>
</div>