
<div class="card-box m-0"> 
<div class="row">	 
	<div class="col-sm-12">
		<a href="#" class="btn btn-outline-primary btn-sm pull-right contacts-create-a"><i class="fa fa-plus"></i> Create Contact</a> 							         
		<h4 class="text-dark header-title m-t-0">Contacts</h4>
	</div>
</div>

<form class="contacts-search-form">
    <input type="hidden" name="action" value="loadContacts"/>

    <div class="row">	
        <div class="col-sm-12">
			<div class="form-group">
				<label class="control-label">Query</label>
				<input type="text" class="form-control" name="filter[q]" placeholder="Search name, email, phone number, etc...">
			</div>
		</div>	
		<div class="col-sm-12">
			<div class="form-group">
				<label class="control-label">Location</label>
				<input type="text" class="form-control" name="filter[loc]" placeholder="Search address, city, state or zip code">
			</div>
		</div>								
		<div class="col-sm-12">
			<div class="form-group">
				<label class="control-label">Type</label>
				<input type="text" class="form-control" name="filter[type]" placeholder="Search type or subtype. Ex: vendor">
			</div>
		</div>		            				
		
        
        <div class="col-sm-8">
            <div class="form-group">                
                <div><a href="#" class="btn btn-primary btn-block contacts-search-a"><i class="fa fa-search"></i> Search</a></div>		
            </div>		
        </div>
		<div class="col-sm-4 text-center">
            <div class="mt-1">Found <b class="contacts-search-count">0</b> Records</div>
        </div>			
	</div>    
</form>

<div class="contacts-container" style="overflow-y: auto; overflow-x: hidden; height: 600px;"></div>

</div>


<script id="template-contacts-item" type="x-handlbars">	
<div class="row">						
	<div class="col-sm-12"><h4>{{name}} <a href="#" class="btn-link contacts-edit-a inline-block small" data-id="{{id}}"><i class="fa fa-edit"></i></a></h4></div>	
	<div class="col-sm-6">							
		<p class="text-muted">{{company}}</p>		
		<div><b>Location:</b> {{address}}, {{city}}, {{state}} {{zip}}</div>
		<div><b>Type:</b> {{type}}</div>
		<div><b>Subtype:</b> {{subtype}}</div>		
		<div><b>Source:</b> {{source}}</div>		
		<div><b>Notes:</b> {{data.notes}}</div>							
	</div>
	<div class="col-sm-6">
		{{#each entries}}
			<div class="inbox-item-date text-dark">
				{{ucwords type}}: 
				{{#xIf type '==' 'phone'}}
					<a href="#" class="dial-btn-a" data-number="{{value}}">{{formatPhoneNumber value}}{{#if title}}<div class="badge badge-sm badge-secondary">{{title}}</div>{{/if}}</a>
					<a href="#" class="btn btn-icon btn-outline-primary btn-sm sms-btn-a" data-number="{{value}}"><i class="fa fa-envelope"></i></a>
				{{else}}
					{{value}}{{#if title}}<div class="badge badge-sm badge-secondary">{{title}}</div>{{/if}}
				{{/xIf}}
			</div>
		{{/each}}
	</div>
	{{#if listing}}
	<div class="col-sm-12">
		<div><b>Assigned Listing:</b> {{listing.title}} - {{listing.full_address}}</div>			
	</div>	
	{{/if}}
</div>												
<hr>		
</script>		