<?php
?>
<form>    
    <input type="hidden" name="action" value="addListing">    
    <div class="row">
        <div class="col-sm-6">
                        
            <div class="form-group">
                <label>Title</label>
                <input type="text" class="form-control" name="title" palceholder="Listing title">
            </div>
            <div class="form-group">
                <label>Address</label>
                <input type="text" class="form-control" name="address" palceholder="">
            </div>
            <div class="form-group">
                <label>State</label>
                <input type="text" class="form-control" name="state" palceholder="">
            </div>
            <div class="form-group">
                <label>Type</label>
                <input type="text" class="form-control" name="category" palceholder="Listing type...">
            </div> 
            <div class="form-group">
                <label>Land Sqft</label>
                <input type="text" class="form-control" name="sqft" palceholder="">
            </div> 
            <div class="form-group">
                <label>NOI</label>
                <input type="text" class="form-control" name="noi" palceholder="">
            </div> 



        </div>
        <div class="col-sm-6">

            <div class="form-group">
                <label>Sales/Lease?</label>
                <select class="form-control" name="type">
                    <option value="sales">Sale</option>
                    <option value="lease">Lease</option>
                </select>
            </div>        
            <div class="form-group">
                <label>City</label>
                <input type="text" class="form-control" name="city" palceholder="">
            </div>
            <div class="form-group">
                <label>Zip</label>
                <input type="text" class="form-control" name="zip" palceholder="">
            </div> 
            <div class="form-group">
                <label>Subtype</label>
                <input type="text" class="form-control" name="subtype" palceholder="Listing subtype...">
            </div> 
            <div class="form-group">
                <label>Bldg Sqft</label>
                <input type="text" class="form-control" name="buildings_sqft" palceholder="">
            </div> 
            <div class="form-group">
                <label>Cap Rate</label>
                <input type="text" class="form-control" name="cap_rate" palceholder="">
            </div>
            <div class="form-group">
                <label>Price</label>
                <input type="text" class="form-control" name="price" palceholder="">
            </div>


        </div>
    </div>

         
</form>
